server.port=8081
message=Chao mung den voi Patient Service tu Config Server
spring.datasource.url=jdbc:postgresql://localhost:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=false
app.welcome=Chào mừng tới BV RikkeiEducation, Test lần 2
